### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by ghost** [C2FO/patio#64]
Hi,

After few hours of use, I receive this error and need to restart the application.

```
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/ubuntu/servers/pinchmanager-backend/node_modules/patio/node_modules/mysql/lib/protocol/Protocol.js:63:13)
    at Socket.onend (stream.js:66:10)
    at Socket.EventEmitter.emit (events.js:126:20)
    at TCP.onread (net.js:418:51)
```

What's the problem ?

**Comment by vikeen** [comment]
@doug-martin. How about this guy?
